services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sas-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-sas_db}
    volumes:
      - mongodb_data:/data/db
      - ./backend/dump:/docker-entrypoint-initdb.d
    networks:
      - sas-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: sas-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-sas_db}?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_LIFETIME=7d
      - FRONTEND_APP_URL=http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - sas-network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: sas-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sas-network

volumes:
  mongodb_data:

networks:
  sas-network:
    driver: bridge
